# Generated by Django 5.1.4 on 2024-12-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="spotify_playlist_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="spotify_track_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
